services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db  

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@1
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog:
    container_name: catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductCollectionName=Products"
      - "DatabaseSettings__BrandCollectionName=Brands"
      - "DatabaseSettings__TypeCollectionName=Types"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket:
    container_name: basket
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379" 
      - "GrpcSettings__DiscountUrl=http://discount:8080" 
    depends_on:
      - basketdb
    ports:
      - "8001:8080"
 
  discount:
    container_name: discount
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;"  
    depends_on:
      discountdb:
        condition: service_healthy        
    ports:
      - "8002:8080"
